name: Deprecated - Do Not Use (Approval)

on:
	workflow_dispatch: {}

jobs:
	noop:
		runs-on: ubuntu-latest
		steps:
			- run: echo "This workflow is deprecated and intentionally disabled. Use CI and Pages workflows instead."
