name: Build and Test Jekyll Site

on:
  # Trigger on pull requests
  pull_request:
    branches: [ main, master ]
  # Trigger on PR reviews
  pull_request_review:
    types: [submitted]

# Sets permissions of the GITHUB_TOKEN to allow reading content
permissions:
  contents: read

jobs:
  # Build job for PR testing
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Ruby for Jekyll
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false

      # Verify Ruby version
      - name: Verify Ruby version
        run: |
          ruby --version
          bundle --version

      # Clear any existing bundle config
      - name: Clear bundle config
        run: |
          rm -rf .bundle
          bundle config --local path vendor/bundle

      # Install dependencies
      - name: Install dependencies
        run: bundle install

      # Build the site with Jekyll
      - name: Build with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: test

      # Test the build
      - name: Test build artifacts
        run: |
          if [ ! -d "_site" ]; then
            echo "Error: _site directory not created"
            exit 1
          fi
          if [ ! -f "_site/index.html" ]; then
            echo "Error: index.html not generated"
            exit 1
          fi
          echo "Build successful - _site directory created with content"
